### ISSUE TITLE
VoltzEngine 1.12 Alpha crash on load (SERVER)

### ISSUE THREAD

**Issue by baggatbt** [BuiltBrokenModding/VoltzEngine#100]
Minecraft Version:
-
Forge Version:
-
VoltzEngine Version:
-
*is this the latest curseforge build?*
https://pastebin.com/fGtWxLzy
---------------------
Crash Report:
----------
Explain issue in detail:
I know this is an alpha version but I figured id drop the report in case its helpful. When starting a server using VoltzEngine it throws an exception. I have confirmed it works fine in a singleplayer world.

**Comment by MrDj200** [comment]
Same here:

Minecraft Version:
- 1.12.2
Forge Version:
- 2606
VoltzEngine Version:
- 1.7.2b12
---------------------
Crash Report:
https://pastebin.com/rGsQqAzw
----------
Explain issue in detail:
Crash on Server start

**Comment by dmodoomsirius** [comment]
Both are in extreme alpha. they are meant for single player goofing off. We are aware things are broken.

**Comment by DarkGuardsman** [comment]
Fixed yesterday https://github.com/VoltzEngine-Project/Engine/commit/87636dbcf5fe11994c278f99e1701638db1446d2
