### ISSUE TITLE
VoltzEngine crashes with something (not sure)

### ISSUE THREAD

**Issue by HeliosHDS** [BuiltBrokenModding/VoltzEngine#28]
Could i have help with this crash report? i have "tried" to install ICBM mod (1.7.10) into a 1.7.10 modpack, at first it said i need VoltzEngine 0.7.2b. After i have installed that minecraft has crashed, i have provided a report on pastebin since it's very long.

http://pastebin.com/AhNBSiiN

I have tried both Java 7 and Java 8 also it did auto download CodingLib-0.0.3b27-universal.

i'm really sorry if this is not the right place to ask about this however anywhere els i would probably not get replied to.

Many thanks.

**Comment by Hennamann** [comment]
This seems to me to be the same error as #27 so try updating Minecraft Forge to version 1248, you're running 1277.

**Comment by dmodoomsirius** [comment]
Voltz engine will son say what forge version it requires I am working on that. Should be ready soon.

**Comment by dmodoomsirius** [comment]
closing
