### ISSUE TITLE
missing texture 

### ISSUE THREAD

**Issue by Devtech223** [BuiltBrokenModding/VoltzEngine#32]
Minecraft Version:1.7.10
Forge Version:??
VoltzEngine Version: 0.9.2b30

----------
Explain issue in detail:
platinum ore is missing a texture

**Comment by dmodoomsirius** [comment]
@DarkGuardsman is aware. i have no clue when a texture will be implemented.

**Comment by DarkGuardsman** [comment]
@dmodoomsirius That issue tracker layout is nice

@Devtech223 Currently the ore is unused so has not been high priority to fix. Plus our texture artist has been too busy to make textures. I'll fix see about fixing it in the next few days. At least maybe place a temp texture.

**Comment by Devtech223** [comment]
ok i just can't take it out do to a bug that if i edit the config it won't work with mechanism mod 
i just added my own texture for now 
@DarkGuardsman
