### ISSUE TITLE
Wire cutter and iron screw recipe loop

### ISSUE THREAD

**Issue by LemADEC** [BuiltBrokenModding/VoltzEngine#36]
Minecraft Version: 1.7.10
Forge Version:10.13.4.1614
VoltzEngine Version: 0.15.10.158158
----------
Explain issue in detail:
According to NEI, Wire cutters are crafted using a iron screw.
The latest is crafted using Wire cutters.
Hence both are unobtainable when checking NEI.

**Comment by dmodoomsirius** [comment]
just to confirm this is the latest build off curse forge right?

**Comment by LemADEC** [comment]
This is the version reported in the log.
File name is VoltzEngine-1.7.10-0.15.10b158-dev-universal.jar, latest found on CurseForge.

**Comment by DarkGuardsman** [comment]
Confirmed, will fix when i get off work/home a 5pm
