### ISSUE TITLE
Voltz Engine OreDict Conflict with Rotarycraft

### ISSUE THREAD

**Issue by Phalanxguard** [BuiltBrokenModding/VoltzEngine#38]
Minecraft Version:
1.7.1
Forge Version:
7.10.99.99
VoltzEngine Version:
V 10b162

---------------------
http://pastebin.com/T7SktmVu
----------
Explain issue in detail:
When inserting any ore into rotarycraft extractor the game crashes, detailed in crash log as conflict with  Voltz Engine ore dictionary entry. Using lastest build (V13a) of Rotarycraft.

Edit: I can also confirm removing Voltz Engine and ICBM from the modpack allows the extractor to function fine.

**Comment by dmodoomsirius** [comment]
Have you told Reika about this yet?

**Comment by Phalanxguard** [comment]
Yes I informed Reika, he didn't comment on fixing it, simply said it was a ore dictionary conflict.
I'm using the latest version of Reika's mods, all V13b except Rotarycraft which is V13a (The latest available on curseforge).

Link to Reika's github submission:
https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/859

**Comment by DarkGuardsman** [comment]
Its an issue on Reika's end as far as I can tell. I'll talk to him when he gets on later today and see whats  exactly wrong. As far as I can tell it looks like he locks resources to one ore value. While forge allows any number of resources per ore value.

**Comment by DarkGuardsman** [comment]
I talked to reika he will be adding a patch for the issue on his end. The cause was exactly what I thought he was doing a one-one recipe. Which would crash at any attempt to register another recipe with the same item. In this exact case it's the aluminum ore which has two ore dictionary names.

**Comment by Phalanxguard** [comment]
Great stuff, thank you, I love both these mods and I'd be torn if I had to choose between! I'll tell my server peeps to avoid using the extractor for now.
