### ISSUE TITLE
[1.7.10] Minecraft Crash (Rendering item)

### ISSUE THREAD

**Issue by MCwind5542** [BuiltBrokenModding/VoltzEngine#45]
Minecraft Version:
-1.7.10
Forge Version:
-![image](https://cloud.githubusercontent.com/assets/21010558/17644579/4002974c-61bd-11e6-80fd-cbed48f3748c.png)

VoltzEngine Version:
-![image](https://cloud.githubusercontent.com/assets/21010558/17644584/4e083e8c-61bd-11e6-9164-26f3b2f959eb.png)

*is this the latest curseforge build?*
**Please Pastebin crash**
---------------------
Crash Report:
----------[crash-2016-08-13_23.52.27-client.txt](https://github.com/BuiltBrokenModding/VoltzEngine/files/416677/crash-2016-08-13_23.52.27-client.txt)

Explain issue in detail:
When I When I search "v" or "eng" in the transmutation table that is in ProjectE , it just crash my game
https://github.com/sinkillerj/ProjectE/issues/1329

**Comment by DarkGuardsman** [comment]
I blame project E but I can add checks to fix it on my end.

**Comment by MaPePeR** [comment]
Yea, its partly ProjectEs fault, but there is not really a lot we could do about this except ASM-ing a try/catch into the Item-Render-Pipeline... and that is not something i would like to do and it would not be a real fix anyway...

**Comment by DarkGuardsman** [comment]
Well validating or spawning the item with its original NBT would fix the problem. As the tools use NBT to figure out what type they are as the metadata is used for damage. I'm seeing this same problem pop up in my other mods. Where Project E is messing with the NBT in some odd way, maybe not directly but it is causing broken items to be spawned.

**Comment by MaPePeR** [comment]
Thats the problem: there is no way to "validate" the NBT... You never really know, which items need to keep their NBT and which not.

**Comment by DarkGuardsman** [comment]
Ya, but then the safe way is to never remove NBT from an item. Then lets mods implement an API to remove their own NBT data as needed. Other wise even if I implement NPE checks on my end the item is broken anyways key point https://github.com/BuiltBrokenModding/ICBM/issues/225. Where the items validation code caught the error but now the item is broken.

**Comment by DarkGuardsman** [comment]
Issue should be fixed https://github.com/BuiltBrokenModding/VoltzEngine/commit/8f744cef681fc324d738c9b25b8f8bb0ba80c02f

Implemented registering the tools with Project E's whitelist. Have yet to fully test it as I don't know how to use Project E. Will learn the mod later and test that the fix fully works. However, for now I will close the issue.
