### ISSUE TITLE
[1.7.10] Minecraft crash on startup

### ISSUE THREAD

**Issue by Kaihatsujin** [BuiltBrokenModding/VoltzEngine#46]
Minecraft Version: 1.7.10
-
Forge Version: 1.7.10 - 10.13.4.1614
-
VoltzEngine Version: VoltzEngine-1.7.10-0.19.0b207-dev-universal
-
*is this the latest curseforge build?* Yes.
**Please Pastebin crash** 
---------------------
Crash Report: http://pastebin.com/H7eSaFCT
----------
Explain issue in detail: After I press play in the launcher, the game almost instantly crashes and gives the above error. This is only a problem with voltz engine, with and without the ICBM mod installed. It works with all the other mods just fine but not with voltz engine.

**Comment by DarkGuardsman** [comment]
Looks like I messed up the IC2 support, will have fixed here sometime this week.

**Comment by Kaihatsujin** [comment]
Thanks!
