### ISSUE TITLE
industrialcraft-2-2.2.823

### ISSUE THREAD

**Issue by SvEgiiVEteR** [BuiltBrokenModding/VoltzEngine#49]
Minecraft Version:
1.7.10
Forge Version:
10.13.4.1614
VoltzEngine Version:
0.19.0b207-dev
*is this the latest curseforge build?*
**Please Pastebin crash**
---------------------
http://pastebin.com/uhZmFHKG
----------
Explain issue in detail:
if I install industrialcraft-2-2.2.823 this error occurs.

**Comment by dmodoomsirius** [comment]
dupelicate of https://github.com/BuiltBrokenModding/VoltzEngine/issues/47
