### ISSUE TITLE
Crash when looking for OC

### ISSUE THREAD

**Issue by dmodoomsirius** [BuiltBrokenModding/VoltzEngine#54]
Minecraft Version: 1.7.10
-
Forge Version: 10.13.4.1614
-
VoltzEngine Version: 0.23.1.282
-
*is this the latest curseforge build?* Latest off CI
**Please Pastebin crash**
---------------------
Crash Report: https://gist.github.com/dmodoomsirius/faae87deb0fa8f427a6eac6c3bab3091
----------
Explain issue in detail: on launch crash trying to look for  a OC class

**Comment by DarkGuardsman** [comment]
When filling out your own bug reports you really do not need to list the forge, ve, or MC version. That is honestly only for users and will only ever be useful when we are maintaining several versions at once.
