### ISSUE TITLE
VE and Enderio Compat issue

### ISSUE THREAD

**Issue by dmodoomsirius** [BuiltBrokenModding/VoltzEngine#56]
Minecraft Version: 1.7.10 
-
Forge Version: 10.13.4.1614
-
VoltzEngine Version: 0.23.1.11
-
Enderio Version: 1.7.10-2.3.0.429_beta
-
*is this the latest curseforge build?* Yes
**Please Pastebin crash**
---------------------
Crash Report: https://gist.github.com/dmodoomsirius/6bff79efeaa8c8b0c2e7c219b3bbdc07
----------
Explain issue in detail:

Crash on load. Does not happen without VoltzEngine

**Comment by dmodoomsirius** [comment]
I can reproduce with just VE, EnderCore and EnderIO, 
https://gist.github.com/dmodoomsirius/3de9d2de38ad5913f4feefaa8ca82cdf

**Comment by zmaster587** [comment]
I'm getting reports of a similar issue with libvulpes and VE.  Also similar thing occuring with VE + buildcraft-7.1.18 ( http://pastebin.com/6bcx13PZ ).  Buildcraft launches fine without VE.

**Comment by DarkGuardsman** [comment]
Ya I'm not sure what is causing this but it is triggering on everything containing COFH energy code. It could be the ASM injector but that shouldn't mess with anything outside of the com.builtbroken package. We also do not ship the API for COFH either so this is very odd.

**Comment by zmaster587** [comment]
I strongly suspect ASM injection of some kind because in the dev env I do not allow any ASM injection by anything other than AR/libVulpes and it loads just fine.  Although there may be other things at play in the dev env.  I'll try enabling ASM from VE in dev env and see if it crashes

**Comment by DarkGuardsman** [comment]
If it is the asm luckily it comes with an off switch in the runtime so could be disabled. As well I'm adding a ton of debug to the ASM to see if it crashes during the transform call. Problem is the ASM should only run on "com.builtbroken" packages and should never mess with other mods.

**Comment by DarkGuardsman** [comment]
https://github.com/BuiltBrokenModding/VoltzEngine/blob/development/src/main/scala/com/builtbroken/mc/core/asm/template/ClassTransformer.java

**Comment by zmaster587** [comment]
err, the configs appear to be empty at runtime...

**Comment by DarkGuardsman** [comment]
Its a system arg to disable the ASM since I would have to write my own config generator to use it as ASM time.

**Comment by zmaster587** [comment]
ahh, makes sense

**Comment by DarkGuardsman** [comment]
-DenableAsmTemplates=false

**Comment by DarkGuardsman** [comment]
hmm just ran VE and EnderIO locally in MultiMC I can confirm it is broken. As well that it can't find anything in the COFH api folder. Something is preventing it from loading but I am unsure what?

**Comment by DarkGuardsman** [comment]
So I can confirm it is not the ASM as it is not touching any of the failed classes. My next theory is that something is breaking how classes are loading. My going to check every place I look for COFH api and tweak it a little bit.
