### ISSUE TITLE
Missing Names

### ISSUE THREAD

**Issue by GreenCafe** [BuiltBrokenModding/VoltzEngine#57]
- [x] item.voltzengine:sheetMetal.metalSheet_eighth.name

- [x] item.voltzengine:gem.quartz.smoky.uncut.name

**Comment by GreenCafe** [comment]
Not exactly missing names but errors on the names: https://youtu.be/kW94TXr5eE4

**Comment by Hennamann** [comment]
Fixed with ce071c1660c43c346addfb970a01f1ee7961e058
