### ISSUE TITLE
ItemFood, invalid constructor error

### ISSUE THREAD

**Issue by Hennamann** [BuiltBrokenModding/VoltzEngine#6]
Whenever i try to create an item that extends the minecraft ItemFood class, the game crashes and voltz engine talks about a invalid constructor even though my constructor was correct. This is probably an error with the way voltzengine handles item constructors. Here's a crash reported generated using military base decor:

http://pastebin.com/NZCFkQ7D

**Comment by DarkGuardsman** [comment]
Going to need a link to your code. As well VE's mod manager if you use the default newItem(ItemClass.class) expects a default constructor. If you want to use a construct with args you have to use the other method.

**Comment by Hennamann** [comment]
Even if i specify the constructor arguments inside the item class itself? As for the code, will have to do that later, off my computer right now.

**Comment by DarkGuardsman** [comment]
all VE's method is looking for is a constructor that looks like 'Public ItemClass()'

So either your constructor has arguments like 'ItemClass(int id)' or its 'protected ItemClass()' or 'private ItemClass()'

**Comment by Hennamann** [comment]
I see, i'l do some tests on it tomorrow(possibly send you the code aswell).
i guess you can mark this as solved now...
