### ISSUE TITLE
Voltz Engine, MFFS, and ICBM Crash

### ISSUE THREAD

**Issue by buttpirate69** [BuiltBrokenModding/VoltzEngine#60]
Minecraft Version:
- 1.7.10
Forge Version:
- 10.13.4.1614-1.7.10
VoltzEngine Version:
- 0.25.0b312
*is this the latest curseforge build?* Yes
**Please Pastebin crash**
---------------------
Crash Report:
MFFS Crash Report: http://pastebin.com/VcuN0qXf
ICBM Crash Report: http://pastebin.com/MqzYkkwH
----------
Explain issue in detail:
Voltz Engine, MFFS version 0.29 and ICBM version 2.14.0b26 are the only mods installed. I tested them independently. MFFS crashed in Creative mode when trying to view page two of the Creative menu. ICBM crashes on startup "Mojang" screen.

**Comment by DarkGuardsman** [comment]
First crash is a null creative tab in MFFS and should already be fixed. We will be uploading a new version here soon.

Second crash I'll look into here shortly but suspect its a minor issue.

**Comment by DarkGuardsman** [comment]
The second issue looks like the wrong VE version is being used with ICBM. Will check what version is uploaded on curse as someone might have neglected to upload the latest when updating ICBM.

**Comment by buttpirate69** [comment]
So should I expect a new version of MFFS and VE to be uploaded to Curse as soon as you get the chance?

**Comment by DarkGuardsman** [comment]
Yes, most likely in the next day or two depending on when @dmodoomsirius has time to do the uploads

**Comment by buttpirate69** [comment]
Thanks!

**Comment by buttpirate69** [comment]
Hey, I noticed a new version of VE and MFFS were uploaded to Curse, but I tried them out and I'm still getting errors. Should I save the error log and submit a new issue report?

**Comment by DarkGuardsman** [comment]
Just append it here so we can see if it is the same problem

**Comment by buttpirate69** [comment]
Alright, so VE and MFFS work by themselves, which is great! But I'm still getting a crash when I use VE and ICBM together:

ICBM 2.14.0.b26 Crash Report: http://pastebin.com/TTyALgxq

**Comment by DarkGuardsman** [comment]
Yout using an old version, latest on curse is 2.15.0 at least

**Comment by buttpirate69** [comment]
Ah, that was it. Thanks!
