### ISSUE TITLE
VoltzEngine : minimum version required is 0.26.0

### ISSUE THREAD

**Issue by Atomosie** [BuiltBrokenModding/VoltzEngine#62]
Minecraft Version:
1.7.10
Forge Version:
10.13.4.1614
VoltzEngine Version:
0.25.6
*is this the latest curse forge build?*
**Please Pastebin crash**
---------------------
Crash Report:
http://pastebin.com/L31599Ad
Explain issue in detail:

Basically, whenever I try to start up Minecraft with VoltzEngine and ICBM, it displays the error "VoltzEngine: minimum version required is 0.26.0" I've even looked for this new version, but I cannot find it anywhere, even non-curse related sites.

**Comment by dmodoomsirius** [comment]
If its off curse then i would have uploaded the correct Voltz engine build. Did you get that build of ICBM off http://builtbroken.com?
