### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by DREIZ3R** [BuiltBrokenModding/VoltzEngine#63]
Minecraft Version:
1.7.10
Forge Version:
10.13.4.1614
VoltzEngine Version:
0.26
*is this the latest curseforge build?* Yes
**Please Pastebin crash**
---------------------
http://pastebin.com/5uMVZrwQ
----------
Explain issue in detail:
Crash on start (client)

**Comment by DarkGuardsman** [comment]
Your missing CodeLib which should have automatically downloaded with VoltzEngine when loaded. If you are running the client it should prompt to download the lib. If you are running the server it should auto force the download. If neither of these are happening you can manually download the lib here http://api.dmodoomsirius.me/com/builtbroken/codinglib/CodingLib/

**Comment by DREIZ3R** [comment]
Codelib is download in mods/1.7.10 but error now

**Comment by DarkGuardsman** [comment]
Same error or a different error? As well can I get the version of VE and coding lib you are using so I can check the file integrity.

**Comment by DREIZ3R** [comment]
Wait pls a test it.

**Comment by DREIZ3R** [comment]
yes. Problem fix.
Codelib is bad hash. 
Now is good thanks.

P.S. DarkGuardsman thank you for your works. I love MFFS and Voltz and ResonantEngine. Atomic Science must be in your work)) I miss..)) In some weeks i will pay you donat for this ;)

Now a have a new problem. Will create new issue
