### ISSUE TITLE
Dont connect to server

### ISSUE THREAD

**Issue by DREIZ3R** [BuiltBrokenModding/VoltzEngine#64]
Minecraft Version:
1.7.10
Forge Version:
Latest
VoltzEngine Version:
Latest
*is this the latest curseforge build?*Yes

---------------------
FORGE LOG CLIENT(server silent):
Netty Client IO #1/ERROR] [FML/]: Failed to connect to server: there are 2 missing blocks and items
[Netty Client IO #1/DEBUG] [FML/]: Missing list: [VoltzEngine:VEHeatedRock, VoltzEngine:VEHeatedRock]
[Netty Client IO #1/TRACE] [FML/]: $HandshakeAck:{2}->FMLHandshakeClientState$8:ERROR
----------
Explain issue in detail:
When i try to connect on server i cann't coz "Fatally missing Blocks and items"

**Comment by DREIZ3R** [comment]
I think i have problem with some config. But i dont know where config VoltzEngine on server or client(don see it).

In single game it work

**Comment by DarkGuardsman** [comment]
bbm folder is the master folder for all mods for the organization

**Comment by DREIZ3R** [comment]
yep. Thanks. Fix it again.

**Comment by DREIZ3R** [comment]
Perfect Support ;)
