### ISSUE TITLE
No Language

### ISSUE THREAD

**Issue by DREIZ3R** [BuiltBrokenModding/VoltzEngine#65]
Minecraft Version:
1.7.10
Forge Version:
latest
VoltzEngine Version:
Latest
---------------------
![2017-02-08_00 20 27](https://cloud.githubusercontent.com/assets/7696828/22712077/8fbac4a4-ed94-11e6-9db7-94272a32e3e8.png)
![2017-02-08_00 20 32](https://cloud.githubusercontent.com/assets/7696828/22712078/8fbb81f0-ed94-11e6-8b28-dec7ef07985a.png)
![2017-02-08_00 20 34](https://cloud.githubusercontent.com/assets/7696828/22712079/8fbc4ae0-ed94-11e6-9d95-ea0d6b1701e1.png)
![2017-02-08_00 20 39](https://cloud.githubusercontent.com/assets/7696828/22712076/8fba8642-ed94-11e6-983c-9bfc8995d130.png)

**Comment by DarkGuardsman** [comment]
Most likely the GUIs are still using some older code that doesn't check for missing localizations. I will have the developer look into it next time he has a break from his classes. As well if I get some spare time from my own work I'll see about fixing it.

**Comment by DREIZ3R** [comment]
Thank you!

**Comment by DarkGuardsman** [comment]
Moved this issue over to the correct repo :)
