### ISSUE TITLE
Unable to edit VoltzEngine config (all worlds fail to load)

### ISSUE THREAD

**Issue by Nocty1501** [BuiltBrokenModding/VoltzEngine#70]
Minecraft Version:
1.7.10
Forge Version:
10.13.4.1558
VoltzEngine Version:
1.2.3.4141
*is this the latest curseforge build?*
Yes.
**Please Pastebin crash**
---------------------
Crash Report:
None
----------
Explain issue in detail:
VoltzEngine's default config file causes it to add every single recipe to the game as well as a ton of ores to the worldgen that don't actually do anything (because there aren't any mods that use them), and changing any recipe/ore to false in the config file causes the game to crash back to the main menu any time a world is loaded/created (hitting "play selected world" sends me back to main menu, same if I try to create a world).

**Comment by dmodoomsirius** [comment]
if there is no crash report can you gist or pastebin the fml-latest.log and the latest.log please?

Also what value did you change to cause this?

**Comment by DarkGuardsman** [comment]
Ya check the run logs, other than that I will take a look into the configs here later.

**Comment by Nocty1501** [comment]
I had to reinstall my modpack with the default config file to avoid the crashes for now, I'll attach a log after testing a few values from the config, but generally it's happened after I changed any of the worldgen settings or any of the forceloadcontent settings. Changing LoadHeatedRocks to false seemed to have the same effect, as well as LoadScrewDriver and LoadSelectionTool. Existing worlds gave a "missing item" error and crashed back to main menu if I opted to proceed anyway, and creating new worlds simply quit me back to title. Any worlds "created" in this way did not show up in the list of worlds in-game, but strangely enough the world files were still present in the saves folder.

Apologies for writing these in crude paragraphs, I'm just really tired right now, haven't slept in hours.
Thanks for the quick reply, too!

**Comment by DarkGuardsman** [comment]
no need to apologize

 anyways the configs are not heavily tested so it is likely that at someone point the content loading was messed up. I need to switch most of it over to JSON soon which should not have this issue. As it does the should load check before creating the items.

**Comment by Nocty1501** [comment]
Aye aye, I'll update you with more details when I have time to test separate config settings and whether they break the game or not.

**Comment by DarkGuardsman** [comment]
Just tested everything with the latest version of VE and ICBM. All disable configs are working and not crashing the game. In order to test what is crashing your game I will need a crash log or a run log.

Edit: https://www.youtube.com/watch?v=M9Wms20USao&feature=youtu.be

**Comment by Nocty1501** [comment]
I'll get back to you when I can gather a run log or a more detailed description of what's happening.
Sorry for the inconvenience!

Edit: I just had to mention how much I appreciate the hands-on work you're doing. This is pretty fucking awesome stuff. Keep it up!
