### ISSUE TITLE
Garnet Ore breaks instantly, even by hand

### ISSUE THREAD

**Issue by Nocty1501** [BuiltBrokenModding/VoltzEngine#71]
Minecraft Version:
1.7.10
Forge Version:
10.13.4.1558
VoltzEngine Version:
1.2.3.4141
*is this the latest curseforge build?*
Yep.
---------------------
Crash Report:
None
----------
Explain issue in detail:
Title. However, it only drops the garnet if you are using an appropriate tool.

**Comment by Nocty1501** [comment]
Update: bug also applies to Red Banded Onyx Ore and Yellow Garnet Ore. Might apply to just all gem ores in general.

**Comment by DarkGuardsman** [comment]
its most likely all gem ores if one is having the problem. Luckily its an easy fix but might be a while before a new build is up as we are having issues with our build servers again.
