### ISSUE TITLE
Trying to start world, gets booted to main menu.

### ISSUE THREAD

**Issue by ThanEEpic** [BuiltBrokenModding/VoltzEngine#73]
**Minecraft Version:**
-1.7.10
**Forge Version:**
-10.13.4.1558
**VoltzEngine Version:**
-VoltzEngine-1.7.10-1.3.0b60
Yes, it is the latest version.
**Pastebin crash:**
There isn't a crash report, but [here's](https://pastebin.com/zKGJB9zM) the console from after I launch the modpack till when I have to kill it. 
**Explain issue in detail:**
Anytime I try to disable option in the config(ore gen, circuits, etc.) and try to load a world, it puts me back into the main menu. When I try to exit the game, it closes but the game stays as a background process and I have to kill it from the launcher console. No crash report is given, but the above link is to the later half of the console.

**Comment by DarkGuardsman** [comment]
Looking at the log the source of the error is Mekanism. However, this issues has been reported before and is related to the disable configs. My theory is the ore dictionary has a few bad values in it. I'm going to look over the VE code here later to see if something is registering a null item and create code to clear out said values. This way not only will it fix issues with VE but other mods having the same issue.

java.lang.NullPointerException
    at net.minecraft.item.ItemStack.func_77960_j(ItemStack.java:217) ~[add.class:?]
    at mekanism.api.util.StackUtils.equalsWildcard(StackUtils.java:63) ~[StackUtils.class:?]
    at mekanism.api.util.StackUtils.equalsWildcardWithNBT(StackUtils.java:68) ~[StackUtils.class:?]
    at mekanism.common.recipe.inputs.ItemStackInput.testEquality(ItemStackInput.java:66) ~[ItemStackInput.class:?]
    at mekanism.common.recipe.inputs.ItemStackInput.testEquality(ItemStackInput.java:8) ~[ItemStackInput.class:?]
    at mekanism.common.recipe.inputs.MachineInput.equals(MachineInput.java:54) ~[MachineInput.class:?]

**Comment by ThanEEpic** [comment]
The gem ores work now, but the regular ores still don't.

**Comment by DarkGuardsman** [comment]
To be honest I've still been unable to replicate the issue myself. I do suspect the primary problem is just with Mekanism caching something. However, I will be moving the ore to JSON here very soon when I recoded it to have a gravel, sand, and cobblestone version. Hopefully, that transition will fix the issue.

**Comment by ThanEEpic** [comment]
Alright I'll keep checking on the new versions. Thank you!
