### ISSUE TITLE
Crash with Armory mod

### ISSUE THREAD

**Issue by LemADEC** [BuiltBrokenModding/VoltzEngine#74]
Minecraft Version:
- 1.7.10
Forge Version:
- 10.13.4.1614 
VoltzEngine Version:
- VoltzEngine-1.7.10-1.4.0b84 + Armory-1.7.10-0.5.0b57
---------------------
Crash Report:
https://pastebin.com/nRgRqBfm
----------
Explain issue in detail:
Trying to place the fence topping block.
I couldn't orient it easily, so I've tried various shift clicking and ended with that crash.

**Comment by DarkGuardsman** [comment]
Not related to Armory but an internal issue in the old Tile prefab. Should be fixed soon but may I ask what fence topping block?

**Comment by DarkGuardsman** [comment]
https://github.com/VoltzEngine-Project/Prefabs/commit/84639ae8af31416aea305133c02fa3ce631c0513

**Comment by LemADEC** [comment]
![image](https://cloud.githubusercontent.com/assets/4776032/26396241/eafa46ec-4072-11e7-82c8-057fe3a49697.png)
militarybasedesor:fence_topper is the registry name.

**Comment by DarkGuardsman** [comment]
That would be military base decor and not armory

**Comment by LemADEC** [comment]
that's pretty correct, lol
