### ISSUE TITLE
VolzEngine Crash on start

### ISSUE THREAD

**Issue by DREIZ3R** [BuiltBrokenModding/VoltzEngine#75]
Minecraft Version:
1.7.10
Forge Version:
latest
VoltzEngine Version:
latest
*is this the latest curseforge build?*
**Please Pastebin crash**
ON CLIENT:
https://pastebin.com/1yFJcrbz
ON SERVER:
https://pastebin.com/c096MrEQ
---------------------

**Comment by DREIZ3R** [comment]
Minecraft Version:
1.7.10
Forge Version:
latest
VoltzEngine Version:
99 VERSION(no have a crash)
AND TPS server is go DOWN when Force field project work more 32 range
Look this.
SERVER TPS SLOW:
![image](https://user-images.githubusercontent.com/7696828/26858906-e493b138-4b3c-11e7-84af-ebf9a24647f5.png)
![image](https://user-images.githubusercontent.com/7696828/26860613-7551d286-4b47-11e7-882f-d0b04a06ff3c.png)
CUBE TOO
Matrix have some bug too when use more then 128 scale.

**Comment by DREIZ3R** [comment]
https://github.com/VoltzEngine-Project/Engine/issues/65
Opened now. http://clip2net.com/clip/m223352/51111-clip-206kb.png?nocache=1

**Comment by dmodoomsirius** [comment]
Similar to https://github.com/BuiltBrokenModding/VoltzEngine-Content/issues/1

**Comment by DREIZ3R** [comment]
In latest version voltzengine and MFFS this crash is fixed. Thanks.
Problem 2 test it now.
Problem 3 actually
