### ISSUE TITLE
Ores missing an unlocalized name

### ISSUE THREAD

**Issue by LemADEC** [BuiltBrokenModding/VoltzEngine#76]
Minecraft Version:
-1.7.10
Forge Version:
- Forge10.13.4.1614
VoltzEngine Version:
- 1.7.10-1.4.0b95

Explain issue in detail:
In SMP, ores are missing an unlocalized name (returning null), this causes issues with UndergroundBiomesConstruct which uses that name to create their owns.

**Comment by DarkGuardsman** [comment]
localized names are client side and that is a poor design on that mods part. Either way I'll look into it but the mod should use registry names.

**Comment by LemADEC** [comment]
UBC definitly could use some thought on its design and implementation, that I completely agree.
I'm confused on why getUnlocalizedName() would be client side only and be allowed to report null. On 1.10, it's still accessible and not supposed to report null.

**Comment by DarkGuardsman** [comment]
Localizations are only loaded client side so it would be assumed it has nothing to do with server logic. That being said its most likely an easy fix but I have yet to look at it.

**Comment by LemADEC** [comment]
Fix is working properly
