### ISSUE TITLE
version 1.6.0 can be used to connect a server running 1.7.1

### ISSUE THREAD

**Issue by LemADEC** [BuiltBrokenModding/VoltzEngine#80]
Minecraft Version:
- 1.7.10
Forge Version:
- 7.99.40.1614
VoltzEngine Version:
- VoltzEngine-1.7.10-1.7.1b141 / 1.7.10-1.6.0b124
Explain issue in detail:
A client running version 1.6.0 can connect to a server running 1.7.1.
I can understand build number is ignored, but the whole version seems like a bug, or is it just server side fixes?

**Comment by DarkGuardsman** [comment]
VE ignored client version due to it being able to be used server side only for commands. Which honestly needs to be changed as its never going to be used for that reason.

**Comment by DarkGuardsman** [comment]
No longer an issue as VoltzEngine now version checks again
