### ISSUE TITLE
Crash on load screen! every time! Missing codinglib?

### ISSUE THREAD

**Issue by sammysam1198** [BuiltBrokenModding/VoltzEngine#89]
Minecraft Version:
- 1.7.10
Forge Version:
-10.13.4.1558-1.7.10
VoltzEngine Version:
-1.7.10-0.29.0b380
*is this the latest curseforge build?*
yes
**Please Pastebin crash**
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: com/builtbroken/icbm/content/warhead/ItemBlockWarhead
---------------------
Crash Report:
----------
Explain issue in detail:
I'm not quite sure about a lot of this stuff as I am not a coder myself but I have been having a lot of issues trying to get the voltz engine to run. I'm not sure where I can get the coding lib for it but there was a notification before the load screen came up that said it was missing the codinglib. if anyone could help me get this thing running I would greatly appreciate it. minecraft wont even start as the game crashes even before it loads to the main menu. if you need any more info please feel free to email me or respond thank you

**Comment by DarkGuardsman** [comment]
It should show a pop-up window asking if you want to download, if you hit yes it will download. Since it seems to not be doing that you can manually download and place it into your mod folder http://api.dmodoomsirius.me/com/builtbroken/codinglib/CodingLib/0.2.8b50/

Its likely in the future this download will be included with VE to avoid this issue.

**Comment by sammysam1198** [comment]
yeah its not downloading and when I go to that address you gave me it just shows a bunch of different links like a files tree and there is no download button anywhere. sorry I'm pretty new to coding I don't know a lot about it

**Comment by DarkGuardsman** [comment]
http://api.dmodoomsirius.me/com/builtbroken/codinglib/CodingLib/0.2.8b50/CodingLib-0.2.8b50.jar
