### ISSUE TITLE
Remove API for delivered jar

### ISSUE THREAD

**Issue by LemADEC** [BuiltBrokenModding/VoltzEngine#98]
Minecraft Version:
- 1.7.10
Forge Version:
- n/a
VoltzEngine Version:
- 1.9.18b385

Explain issue in detail:
Delivered jar includes APIs from other mods, instead of just referring them as dependencies during compilation.
This cause incompatibilities with other mods like this one https://github.com/BuiltBrokenModding/ICBM-Classic/issues/75

**Comment by DarkGuardsman** [comment]
It's really only an issue with outdated mods. However, both will be moved to the API folder once the wrapper system is finished. Right now its easier to directly apply the APIs and include them to save time.

**Comment by LemADEC** [comment]
I'm using the FML provided annotation to remove API from my deliverables
```
@Optional.Method(modid = "ComputerCraft")
```
This forces me to have separate method for each mod and only call said method if the mod is present.

I'm not sure what you mean with your API folder here.
