### ISSUE TITLE
RadarMap lag in SMP

### ISSUE THREAD

**Issue by LemADEC** [BuiltBrokenModding/VoltzEngine#99]
Minecraft Version:
- 1.7.10
Forge Version:
- 1614
VoltzEngine Version:
- 1.9.18b385
Explain issue in detail:
![image](https://user-images.githubusercontent.com/4776032/34908725-8a66a9ee-f894-11e7-9f12-af94df7c05cb.png)
This is with approximately 5 players, 170 entities, 15k tiles

**Comment by DarkGuardsman** [comment]
If I recall right this was solved and was the tile map.
